language: node_js
node_js:
  - 10

install:
  - yarn

script:
  - yarn run build
  - yarn run build:webpack

sudo: false

notifications:
  email: false

branches:
  only:
    - master